resources:
 repositories:
   - repository: utilities
     type: git
     name: Utilities

pool:
  vmImage: 'ubuntu-latest'

trigger:
  branches:
    include:
    - master

steps:
  - template: BuildTemplates/BuildAngularApp.yaml@utilities
    parameters: 
      projectName: CodeTech.Web
      configuration: production
      outputPath: $(Build.ArtifactStagingDirectory)
  - task: Docker@2
    inputs:
      containerRegistry: 'DockerContainerRegistry'
      repository: 'CodeTech.Web'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
  - task: CopyFiles@2
    inputs:
      SourceFolder: KubernetesConfigurations@utilities
      Contents: 'Codetech.Web.Deployment.yaml'
      CleanTargetFolder: true
      TargetFolder: $(Build.ArtifactStagingDirectory)